config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "qwerty"

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def about
    @heading = 'О нас'
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "qwerty", except: [:index, :show]
  def index
    @post = Post.all
  end

  def new
    @post=Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalJob</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
    </a>
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><span class="nav-link px-2 link-dark"><%= link_to "Главная", home_path %></span></li>
      <li><span class="nav-link px-2 link-dark"><%= link_to "О нас", about_path %></span></li>
    </ul>

    <div class="col-md-3 text-end">
      <span type="button" class="btn btn-outline-primary me-2"><%= link_to "Добавить", new_post_path %></span>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>

app/views/posts/edit.html.erb
<h2>Редактирование поста</h2>
<%= form_for @post, data: { turbo: false }  do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название<br>
    <%= f.text_field(:title,{:class => 'form-control'}) %>
  </p>
  <p>
    Текст статьи<br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Все посты</h1>
<% @post.each do |post| %>
  <div class="alert alert-light">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Читать далее", post_path(post), :class => 'btn btn-outline-primary'%>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление поста</h2>
<%= form_for :post, url: posts_path, data: { turbo: false }  do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
<p>
  Название<br>
  <%= f.text_field(:title,{:class => 'form-control'}) %>
</p>
  <p>
    Текст статьи<br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= button_to "Удалить", post_path(@post), method: :delete, data: {confirm: "Удаляем?"}, :class => 'btn btn-danger' %>
<hr>
<h2>Все комментарии</h2>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.username %></strong>: <%=comment.body %></p>
  </div>
<% end %>

<hr>
<h2>Добавление Комментария</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    Пользователь<br>
    <%= f.text_field(:username,{:class => 'form-control'}) %>
  </p>
  <p>
    Текст комментария<br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("добавить", {:class => 'btn btn-success'}) %>
  </p>
<% end %>